### ISSUE TITLE
the docker container will exit after a while

### ISSUE THREAD

**Issue by heiyanbin** [xeden3/MSSpeechServer#2]
when first bring up the container, it's ok. But after a while it will terminate by itself. (Ididn't send any request to it) the error log is:
<img width="1609" alt="image" src="https://github.com/xeden3/MSSpeechServer/assets/7346296/d436bcec-a6b6-47ec-af08-3421e3eb5b87">

**Comment by xeden3** [comment]
I would like to ask if this problem has been solved? Is it related to the docker server environment?

**Comment by heiyanbin** [comment]
Not solved，and  it' not  caused by docker environment.
I looks into the related code a little bit, it seems caused by not catching exception, so the entire process exited.
Seems easy to fix, but I 'm a linux user, I don't know how to build c# project...
![image](https://github.com/xeden3/MSSpeechServer/assets/7346296/9bc641fd-34a9-4b52-8242-a05ada95072e)
![image](https://github.com/xeden3/MSSpeechServer/assets/7346296/8f115dd5-7638-44f2-a1ee-d25d619102c5)

**Comment by xeden3** [comment]
I have updated the exe file to GitHub. You can download it to the container using the following link:

https://github.com/xeden3/MSSpeechServer/blob/main/bin/MSSpeechServer.exe

If the test is successful, please let me know, and I will update Docker Hub later.

**Comment by heiyanbin** [comment]
I pulled the latest commit and rebuilt the docker image.
so far the container is up quite a while (longer than it used to live), I think the problem is gone.

**Comment by xeden3** [comment]
Great ..
