### ISSUE TITLE
500 Server internal error when using japanese voice "Microsoft Server Speech Text to Speech Voice (ja-JP, Haruka)"

### ISSUE THREAD

**Issue by heiyanbin** [xeden3/MSSpeechServer#3]
I can see the voice in the GetVoices call:
<img width="646" alt="image" src="https://github.com/xeden3/MSSpeechServer/assets/7346296/31e1de79-117a-4a13-877e-b41b797d5c16">

But when I try to do tts using the voice "Microsoft Server Speech Text to Speech Voice (ja-JP, Haruka)", it just return a 500 error. and the backend server didn't print any useful log.
![image](https://github.com/xeden3/MSSpeechServer/assets/7346296/522857f3-3fdb-417d-92ca-e7753ad3aea3)

other languages/voices is fine.

**Comment by xeden3** [comment]
Thank you very much for your issues. It seems that you have deeply used and solved some problems. 

Regarding the 500 error that occurs with Japanese TTS, I modified the C# code to print out the error messages. 
![image](https://github.com/xeden3/MSSpeechServer/assets/38025067/97dc2cd8-7c57-47ab-af2c-d1d92be47529)

This shows an 80004005 error, which is a COM call error. It seems that during the Japanese TTS process, the engine calls other DLLs. Therefore, I used the Process Monitor tool on my machine to analyze the differences in DLL calls between Japanese and English TTS processes. By analyzing the logs, I found several suspicious DLLs.
![image](https://github.com/xeden3/MSSpeechServer/assets/38025067/f889f82c-d8e2-4ad4-9e41-4c11a8ba0d68)
![image](https://github.com/xeden3/MSSpeechServer/assets/38025067/791e03ac-9839-4f4c-98c4-5470023cade2)
![image](https://github.com/xeden3/MSSpeechServer/assets/38025067/0e48815b-5b97-461f-bd3f-6cebe119ab8f)

I placed these suspicious DLLs into the Wine environment, and then the following error was reported:
![image](https://github.com/xeden3/MSSpeechServer/assets/38025067/bcbfcfd6-a63e-42ba-91c8-f4932caa68cc)

This proves that the missing DLLs caused the issue, but I still haven't found a way to solve the "Bad EXE format" error. I will look into this further when I have time. Unfortunately, Wine itself is a very unstable environment, and the problems encountered may not be fully resolved.

I have attached two logs for you to download and view.

[en-request.CSV](https://github.com/user-attachments/files/15605545/en-request.CSV)
[jp-request.CSV](https://github.com/user-attachments/files/15605546/jp-request.CSV)

**Comment by xeden3** [comment]
Fortunately, I tested a version of the `NaturalLanguage6.dll` file. Copying it to the `system32` folder resolves the issue. I have already uploaded the latest Docker image to Docker Hub, version v2, and the code has been updated accordingly.
![image](https://github.com/xeden3/MSSpeechServer/assets/38025067/fb05f82c-7d7a-42fa-9d32-e29e053d12cb)

You can pull it using:
```
docker pull xeden3/msspeechserver:v2
```
