### ISSUE TITLE
How to add "es" voices?

### ISSUE THREAD

**Issue by jimibilibob** [xeden3/MSSpeechServer#5]
I've been trying to add spanish voices, even if I add 3 different msi voice files at `libs/language_packs_for_v11` `[MSSpeech_SR_es-ES_TELE.msi, MSSpeech_SR_es-MX_TELE.msi, MSSpeech_TTS_es-MX_Hilda.msi]`, the server only recognizes the one for `Microsoft Server Speech Text to Speech Voice (es-MX, Hilda)`, I did not understand the reason of this behavior.
Is there anything I'm missing?

**Comment by xeden3** [comment]
MSSpeech_SR_es-ES_TELE.msi and MSSpeech_SR_es-MX_TELE.msi are **(SR)** speech recognition packages,  not TTS package. Only the TTS package can take effect.
